#!/bin/bash

me=$(oc whoami 2>&1)

if [[ "$me" == *"admin"* ]]; then
  echo "Already logged in"
else
  echo "Logging in ..."
  oc login https://master.xv33.acumena-os.com --insecure-skip-tls-verify=true -p Xv.1234 -u admin > /dev/null
fi

echo "Starting up the cluster..."
oc project workshop-infra

dcs=( "labs" "gitlab-ce-redis" "gitlab-ce-postgresql" "gitlab-ce" "mysql-pad" "etherpad" )

for app in "${dcs[@]}"
do
  pods=$(oc get dc/$app -o jsonpath='{.status.replicas}' -n workshop-infra)

  if [[ "$pods" == "0" ]]; then
    echo "Scaling up $app..."
    oc scale dc/$app --replicas=1 -n workshop-infra

    # Properly monitor through RC
    # while [ "$pods" != "0" ]
    # do
    #   echo -e "Waiting for $app to be scaled down..."
    #   sleep 5
    #   break
    # done
  fi

  echo "$app has 1 replica running"
done
