#!/bin/bash
oc login https://master.xv33.acumena-os.com --insecure-skip-tls-verify=true -p Xv.1234 -u admin
oc get nodes
for i in `seq -w 01 99`;
do
   result=$(curl -s1 http://gitlab-ce-workshop-infra.cloudapps.xv33.acumena-os.com/user$i/nationalparks/blob/1.2.0/src/main/java/com/openshift/evg/roadshow/parks/rest/BackendController.java | grep "47.039304" | grep '\"National Parks\"')
   if [ "$result" == "" ]; then
      echo "$i has been changed"
   fi
   result=$(curl -s1 http://gitlab-ce-workshop-infra.cloudapps.xv33.acumena-os.com/user$i/nationalparks/settings/integrations?private_token=fR7RH2JGwSZnwr3jvroZ | grep "master.xv33.acumena-os.com/oapi")
   if [ "$result" != "" ]; then
      echo "$i HAS a webhook"
   fi
done
